### ISSUE TITLE
Uncaught TypeError: Cannot read property 'updateLinesInDom' of undefined

### ISSUE THREAD

**Issue by Mentis** [mark-hahn/view-tail-large-files#15]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.198.0
**System**: linux 3.18.9-031809-generic
**Thrown From**: [view-tail-large-files](https://github.com/mark-hahn/view-tail-large-files) package, v0.1.14

### Stack Trace

Uncaught TypeError: Cannot read property 'updateLinesInDom' of undefined

```
At /home/dzmitry/.atom/packages/view-tail-large-files/lib/file-view.coffee:101

TypeError: Cannot read property 'updateLinesInDom' of undefined
  at FileView.module.exports.FileView.setScroll (/home/dzmitry/.atom/packages/view-tail-large-files/lib/file-view.coffee:101:13)
  at FileView.module.exports.FileView.mouseEvent (/home/dzmitry/.atom/packages/view-tail-large-files/lib/file-view.coffee:155:10)
  at HTMLDivElement.<anonymous> (/home/dzmitry/.atom/packages/view-tail-large-files/lib/file-view.coffee:169:56)
  at HTMLDivElement.handler (/opt/atom/resources/app.asar/src/space-pen-extensions.js:112:34)
  at HTMLDivElement.jQuery.event.dispatch (/opt/atom/resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDivElement.elemData.handle (/opt/atom/resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app.asar/src/command-registry.js:238:29)
  at /opt/atom/resources/app.asar/src/command-registry.js:3:61
  at EventEmitter.ipc.sendSync (/opt/atom/resources/atom.asar/renderer/api/lib/ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as getSize] (/opt/atom/resources/atom.asar/renderer/api/lib/remote.js:110:29)
  at Atom.module.exports.Atom.getWindowDimensions (/opt/atom/resources/app.asar/src/atom.js:518:29)
  at Atom.module.exports.Atom.storeDefaultWindowDimensions (/opt/atom/resources/app.asar/src/atom.js:550:25)
  at /opt/atom/resources/app.asar/src/window-event-handler.js:103:21
  at handler (/opt/atom/resources/app.asar/src/space-pen-extensions.js:115:32)
  at jQuery.event.dispatch (/opt/atom/resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
  at elemData.handle (/opt/atom/resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-dark-syntax"
    ]
  },
  "view-tail-large-files": {}
}
```

### Installed Packages

```coffee
# User
view-tail-large-files, v0.1.14

# Dev
No dev packages
```

**Comment by mark-hahn** [comment]
Thanks very much.  Fixed in 0.1.15.
