### ISSUE TITLE
Uncaught ReferenceError: item is not defined

### ISSUE THREAD

**Issue by dnauck** [mark-hahn/view-tail-large-files#19]
[Enter steps to reproduce below:]

1. Open file to monitor
2. open settings tab, switch back to tail tab

**Atom Version**: 0.204.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [view-tail-large-files](https://github.com/mark-hahn/view-tail-large-files) package, v0.1.16

### Stack Trace

Uncaught ReferenceError: item is not defined

```
At C:\Users\danie_000\.atom\packages\view-tail-large-files\lib\file-view.coffee:86

ReferenceError: item is not defined
  at atom-workspace.sub.atom.commands.add.pane:item-removed (C:\Users\danie_000\.atom\packages\view-tail-large-files\lib\file-view.coffee:86:10)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\danie_000\AppData\Local\atom\app-0.204.0\resources\app.asar\src\command-registry.js:238:29)
  at CommandRegistry.handleCommandEvent (C:\Users\danie_000\AppData\Local\atom\app-0.204.0\resources\app.asar\src\command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\danie_000\AppData\Local\atom\app-0.204.0\resources\app.asar\src\command-registry.js:153:19)
  at PaneView.jQuery.fn.trigger (C:\Users\danie_000\AppData\Local\atom\app-0.204.0\resources\app.asar\src\space-pen-extensions.js:64:23)
  at PaneView.module.exports.PaneView.onItemRemoved (C:\Users\danie_000\AppData\Local\atom\app-0.204.0\resources\app.asar\src\pane-view.js:194:19)
  at C:\Users\danie_000\AppData\Local\atom\app-0.204.0\resources\app.asar\src\pane-view.js:3:61
  at Emitter.module.exports.Emitter.emit (C:\Users\danie_000\AppData\Local\atom\app-0.204.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at Pane.module.exports.Pane.removeItem (C:\Users\danie_000\AppData\Local\atom\app-0.204.0\resources\app.asar\src\pane.js:379:20)
  at Pane.module.exports.Pane.destroyItem (C:\Users\danie_000\AppData\Local\atom\app-0.204.0\resources\app.asar\src\pane.js:442:16)
  at HTMLDivElement.<anonymous> (C:\Users\danie_000\AppData\Local\atom\app-0.204.0\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:183:22)
  at space-pen-ul.jQuery.event.dispatch (C:\Users\danie_000\AppData\Local\atom\app-0.204.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
  at space-pen-ul.elemData.handle (C:\Users\danie_000\AppData\Local\atom\app-0.204.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)

```

### Commands

```
     -0:46.1.0 view-tail-large-files:open (atom-text-editor.editor.is-focused)
     -0:14.3.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {},
  "view-tail-large-files": {}
}
```

### Installed Packages

```coffee
# User
view-tail-large-files, v0.1.16
windows-context-menu, v0.3.1

# Dev
No dev packages
```

**Comment by mark-hahn** [comment]
thanks.  Fixed in 0.1.17.
