### ISSUE TITLE
This package is deprecated since Atom supports larger files now.

### ISSUE THREAD

**Issue by mark-hahn** [mark-hahn/view-tail-large-files#21]
**This package is deprecated since Atom supports larger files now.  The tail functionality will be implemented in a new package by itself ASAP.**

**Comment by kankaristo** [comment]
Is this a good place to track for the release of the tail package?

No hurry though, thanks for creating this package. :+1:

**Comment by mark-hahn** [comment]
> Is this a good place to track for the release of the tail package?

Sure, but it may take a while.  One reason I deprecated this is because I
have been too busy.

**Comment by houseoftech** [comment]
> This package is deprecated since Atom supports larger files now. The tail functionality will be implemented in a new package by itself ASAP.

This package will support a multi-gigabyte file, which Atom certainly won't. I'm having trouble opening anything larger than 10MB in Atom, so your package would certainly be useful.

**Comment by mark-hahn** [comment]
I've noticed that also.  Does it still work?

**Comment by houseoftech** [comment]
No, unfortunately.

```
Failed to activate the view-tail-large-files package
Cannot find module 'event-kit'
Hide Stack Trace
Error: Cannot find module 'event-kit'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/corie/.atom/packages/view-tail-large-files/lib/plugin-mgr.coffee:4:13)
    at Object.<anonymous> (/Users/corie/.atom/packages/view-tail-large-files/lib/plugin-mgr.coffee:4:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at ViewTailLargeFiles.activate (/Users/corie/.atom/packages/view-tail-large-files/lib/view-tail-large-files.coffee:26:18)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:181:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:155:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
```

**Comment by mark-hahn** [comment]
I don't remember any event-kit module.  You might try installing event kit
by doing 'npm i event-kit' while in the directory.

**Comment by houseoftech** [comment]
Looks like event-kit is a library already included in Atom.

**Comment by mark-hahn** [comment]
That is weird.  I'll look into it when I am not buried.  Feel free to fix
it and give me a PR (grin).
